services:
  - type: web
    name: brain-tumor-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free

    envVars:
      - key: MODEL_PATH
        value: /app/api/models/best.pt

      - key: MAX_FILE_SIZE_MB
        value: "10"

      - key: CONFIDENCE_THRESHOLD
        value: "0.5"

      - key: API_URL
        value: http://127.0.0.1:8000

      - key: ALLOWED_ORIGINS
        value: "*"